# Generated by Django 3.1.13 on 2021-08-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210820_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='images', verbose_name='Imagen'),
        ),
    ]
