# Generated by Django 3.1.13 on 2021-09-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='', max_length=30, verbose_name='Marca'),
        ),
    ]
